# Generated by Django 5.2.1 on 2025-06-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
